### ISSUE TITLE
Syncing with Firefox is not working

### ISSUE THREAD

**Issue by Sesivany** [flathub/org.gnome.Eolie#13]
When I try to connect to my Firefox account it says the syncing is not working because there is no module called 'cryptography'.

**Comment by bilelmoussaoui** [comment]
Sorry for the long delay, just seen this issue.
the module is there https://github.com/flathub/org.gnome.Eolie/blob/master/org.gnome.Eolie.json#L204. I'm going to push an update right now to use 0.9.45, please let me know once you got the new update if everything works as expected or not.

**Comment by bilelmoussaoui** [comment]
Any news?

**Comment by Sesivany** [comment]
I've got the 0.9.45 version from Flathub and I still experience the issue.

**Comment by biswasab** [comment]
Looks like the python3 module "cryptography" has not met all of it's dependencies. I don't know why the maintainer is inactive but I will try to fix it.

**Comment by bilelmoussaoui** [comment]
Fixed by https://github.com/flathub/org.gnome.Eolie/pull/25
