### ISSUE TITLE
Update to v0.9.60

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Eolie#16]

**Comment by qnixsynapse** [comment]
Does anyone know why it is not being updated?

**Comment by bilelmoussaoui** [comment]
Because I have a lot of others things to maintain :/ I will merge your PR, I need to figure out how to build crypto module in order to fix Firefox sync

**Comment by qnixsynapse** [comment]
@bilelmoussaoui oh. Okay. I am too looking at why cryptography module is failing to install. Will open a PR if I find anything.

**Comment by bilelmoussaoui** [comment]
Thank you!

**Comment by biswasab** [comment]
@bilelmoussaoui  Good news! I have working sync.!

![Screenshot from 2019-04-10 00-29-07](https://user-images.githubusercontent.com/17230826/55827421-bd57a280-5b27-11e9-8435-80fec5f2db52.png)
