### ISSUE TITLE
Install error: GPG signatures found but none in trusted keyring

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.Eolie#2]
https://github.com/gnumdk/eolie/issues/241

@TingPing Any idea?

**Comment by mcclurgm** [comment]
New developments (original poster of the referenced bug). I finally came to my senses and tried to download it direct from the Flathub site. Worked fine this time, not a hitch. Added flathub as shown on their homepage, downloaded Eolie from the applications page, and 'flapak install'ed.

To double check I downloaded the flatpakref from the Eolie github page (https://gnumdk.github.io/eolie-web/) and tried installing it, but it still had the same issue as before. I also looked at the contents of the two flatpakref files and they're quite different, including a massively different GPG key. Is there a chance the one on the Github file is old?

**Comment by barthalion** [comment]
Eolie website should be changed to point to [flatpakref](https://flathub.org/repo/appstream/org.gnome.Eolie.flatpakref) generated by Flathub.

**Comment by ghost** [comment]
^ ping @gnumdk

**Comment by mcclurgm** [comment]
I know it's been a while, but... @Barthalion did you actually update the site or was that just a suggestion? Because if you updated it didn't seem to go through. I'm still getting the old version of the file.

**Comment by barthalion** [comment]
It was a suggestion, I'd say that Eolie website is beyond our jurisdiction.

**Comment by mcclurgm** [comment]
Ah. Thought you were a maintainer somehow. Carry on

**Comment by bilelmoussaoui** [comment]
Eolie's website doesn't exists anymore as far as I know.
