### ISSUE TITLE
Revisit dconf permissions

### ISSUE THREAD

**Issue by nanonyme** [flathub/org.gnome.Eolie#21]
There's currently --filesystem=~/.config/dconf:rw for this app. Should be investigated whether this is really necessary. None of the other apps seem to have this wide permissions and that's not at all what https://docs.flatpak.org/en/latest/sandbox-permissions.html#dconf-access advices.

**Comment by bilelmoussaoui** [comment]
Thanks for reporting those issues. PR are appreciated.
