### ISSUE TITLE
Add OARS data

### ISSUE THREAD

**Issue by nanonyme** [flathub/org.gnome.Eolie#24]
This is apparently now mandatory and makes builds fail.

**Comment by nanonyme** [comment]
https://flathub.org/builds/#/builders/48/builds/529
```
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
Validation of files failed
```

**Comment by nanonyme** [comment]
Based on IRC discussion it only makes test builds fail (which is annoying though).

**Comment by bilelmoussaoui** [comment]
Well, that should be reported upstream. I don't want to carry patches here :/

**Comment by Erick555** [comment]
It's fatal also for official builds: https://flathub.org/builds/#/builders/32/builds/4556

Without fixing it this repo is basically dead.

**Comment by bilelmoussaoui** [comment]
Added and patch sent upstream.
