### ISSUE TITLE
Update to last release

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/org.gnome.Eolie#27]
Flatpak package is out of sync with current release.

**Comment by bellegarde-c** [comment]
@bilelmoussaoui I'm migrating to Silverblue and so I'm now using flatpak.

Do you think you can bring me access to Eolie/Lollypop repository so I can update package on new release ?

**Comment by bilelmoussaoui** [comment]
Done

**Comment by bellegarde-c** [comment]
Thanks

**Comment by bilelmoussaoui** [comment]
let me know if I can help somehow, Lollypop has been kept pretty up to date thanks to the work of @Eonfge. As both apps are in python, you might find this useful https://github.com/flatpak/flatpak-builder-tools/tree/master/pip it mostly a script that generates a flatpak manifest from a requirements.txt file which ease the updates/maintenance a lot

**Comment by Eonfge** [comment]
I was on holiday, so I couldn't attend to my repo duties while camping in the mountains. Over the next couple of days, I hope to catch up with all the outstanding version changes :scream:

**Comment by Eonfge** [comment]
@bellegarde-c can you include an up-to-date requirements.txt file in the main project? I've ran into a circular issue where you tell me to look at the manifest file for all dependencies, but they seem to cause conflicts.

Here my current WIP branch:
https://github.com/Eonfge/org.gnome.Eolie/tree/UpdateEolie

**Comment by danrobi11** [comment]
> all the outstanding version changes

Indeed! Im running the master branch and it runs so much better than the flatpak version. I dont know whats the holdup but it would be very nice for flatpak users to be able to run the latest/greatest ;)  Thank you for the flatpak support :+1:

**Comment by bellegarde-c** [comment]
Hmm, sorry did not see this one. On my TODO list ;)

**Comment by daemonspudguy** [comment]
So, it's still over a year out of date.

**Comment by bellegarde-c** [comment]
@Eonfge What error ?

**Comment by bellegarde-c** [comment]
And feel free to open issues on Eolie/Lollypop gitlab for packaging issue, I will always help ;)

**Comment by Eonfge** [comment]
@bellegarde-c Honestly, I can't recall.If the latest version works, you should move on and ignore my comment.

**Comment by bellegarde-c** [comment]
Ok, found by switching to flatpak build in Builder.

You are missing a schema not available in Gnome Plateform.

For next release (coming soon), you will have to add -Dflatpak=true

**Comment by daemonspudguy** [comment]
@bellegarde-c you forgot a trademark symbol after soon.

**Comment by bellegarde-c** [comment]
https://gitlab.gnome.org/World/eolie/-/tags/0.9.101

Don't forget to:
* add  -Dflatpak=true
* Update PyFXA version to 0.7.7
* Update requests-hawk version to 1.1.0

**Comment by danrobi11** [comment]
Thanks for the update, much appreciated!
