### ISSUE TITLE
Appdata ID should be patched

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.gnome.Eolie#5]
Due to a bug in flatpak, the appdata ID needs to be  `<id>org.gnome.Eolie.desktop</id>` until a version containing the fix is used by Flathub.

Cf. https://github.com/flathub/flathub/pull/161#discussion_r168591146

**Comment by TingPing** [comment]
Personally I think we wait for a proper fix. Like half a dozen apps have the issue and patching them just creates a mess.

**Comment by nedrichards** [comment]
Agree. We've just built and released an FDo runtime with a candidate fix. KDE and GNOME builds should be cascading now. When that's done we can rebuild.

**Comment by Alexander-Wilms** [comment]
Makes sense
