### ISSUE TITLE
Missing metadata on flathub website

### ISSUE THREAD

**Issue by afranke** [flathub/org.gnome.Eolie#6]
While browsing the Network category, I saw an app with no name. Clicked on it, turns out it’s Eolie.
https://flathub.org/apps/details/org.gnome.Eolie

That page has a lot of information missing.

**Comment by TingPing** [comment]
The appdata file is fine, its an issue elsewhere.

**Comment by bilelmoussaoui** [comment]
It's an upstream issue.
